export type PromptCategory = 'image' | 'video' | 'sns';
export type AITool = 'midjourney' | 'dall-e' | 'stable-diffusion' | 'sora' | 'runway' | 'kling';

export interface PromptItem {
  id: string;
  industryId: string;
  category: PromptCategory;
  title: string;
  prompt: string;
  description: string;
  tools: AITool[];
  tags: string[];
  tip?: string;
}

export interface IndustryMeta {
  id: string;
  name: string;
  emoji: string;
  color: string;
  bg: string;
}

export const INDUSTRY_META: IndustryMeta[] = [
  { id: 'restaurant', name: '식당', emoji: '🍽️', color: 'text-amber-700', bg: 'bg-amber-100' },
  { id: 'cafe',       name: '카페·베이커리', emoji: '☕', color: 'text-orange-700', bg: 'bg-orange-100' },
  { id: 'beauty',     name: '미용실·헤어샵', emoji: '✂️', color: 'text-pink-700', bg: 'bg-pink-100' },
  { id: 'clinic',     name: '병원·의원', emoji: '🏥', color: 'text-red-700', bg: 'bg-red-100' },
  { id: 'fitness',    name: '헬스·피트니스', emoji: '💪', color: 'text-violet-700', bg: 'bg-violet-100' },
  { id: 'accommodation', name: '숙박·펜션', emoji: '🏨', color: 'text-teal-700', bg: 'bg-teal-100' },
  { id: 'shopping',   name: '쇼핑·의류', emoji: '🛍️', color: 'text-rose-700', bg: 'bg-rose-100' },
  { id: 'education',  name: '학원·교육', emoji: '📚', color: 'text-indigo-700', bg: 'bg-indigo-100' },
];

export const ALL_PROMPTS: PromptItem[] = [

  /* ─────────────────── 식당 ─────────────────── */
  {
    id: 'res-img-1',
    industryId: 'restaurant',
    category: 'image',
    title: '메뉴 플랫레이 사진',
    prompt: 'Professional overhead flat lay food photography, Korean bibimbap in traditional black stone dolsot bowl, colorful banchan side dishes arranged symmetrically around it, vibrant vegetables with sesame oil sheen, soft diffused natural window light from the left, white linen tablecloth, food styling, Canon EOS R5 85mm, 8K ultra detail, commercial quality --ar 1:1 --v 6.1 --style raw',
    description: '메뉴판·홈페이지·SNS에 바로 활용할 수 있는 상단 평면 메뉴 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['플랫레이', '오버헤드', '메뉴촬영', '음식사진'],
    tip: '메뉴 이름을 Korean [음식명]으로 구체적으로 교체하면 더 정확한 결과를 얻어요',
  },
  {
    id: 'res-img-2',
    industryId: 'restaurant',
    category: 'image',
    title: '드라마틱 메뉴 히어로샷',
    prompt: 'Korean doenjang jjigae bubbling in rustic brown clay pot, dramatic backlit rising steam, dark moody wooden table background, warm golden side lighting, bokeh depth of field, micro condensation on pot, cinematic food editorial photography, 85mm f/1.8, Nikon Z9 --ar 3:4 --v 6.1 --style raw',
    description: '스팀과 조명을 활용한 고급스러운 대표 메뉴 홍보용 히어로샷',
    tools: ['midjourney', 'stable-diffusion'],
    tags: ['히어로샷', '스팀', '드라마틱', '조명'],
    tip: '실제 촬영 시 뒤에서 LED 조명을 쏘면 스팀이 극적으로 표현됩니다',
  },
  {
    id: 'res-img-3',
    industryId: 'restaurant',
    category: 'image',
    title: '레스토랑 인테리어',
    prompt: 'Interior of a modern Korean restaurant, warm Edison bulb pendant lights, rich walnut wood tables, white ceramic tableware, architectural interior photography, soft bokeh of dining guests in background, golden hour sunlight streaming through large windows, lifestyle editorial, medium format film aesthetic --ar 16:9 --v 6.1',
    description: 'Google 마이비즈니스·홈페이지 커버에 사용할 매장 분위기 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['인테리어', '분위기', '골든아워', '건축사진'],
  },
  {
    id: 'res-img-4',
    industryId: 'restaurant',
    category: 'image',
    title: '셰프 포트레이트',
    prompt: 'Portrait of Korean head chef in crisp white uniform, carefully plating a dish on clean slate surface, dramatic Rembrandt side lighting, blurred professional kitchen background, pride and focus expression, editorial portrait photography, Sony A1 50mm, warm color grade, depth of field --ar 3:4 --v 6.1',
    description: '브랜드 신뢰도를 높이는 셰프·스태프 소개 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['셰프', '포트레이트', '인물사진', '브랜딩'],
    tip: '실제 촬영 시 주방 내부 배경보다 흰 벽 앞이 더 깔끔하게 나와요',
  },
  {
    id: 'res-vid-1',
    industryId: 'restaurant',
    category: 'video',
    title: '시즐 홍보 영상',
    prompt: 'Cinematic 4K slow motion macro, Korean galbi beef short ribs sizzling on cast iron grill, intense golden Maillard browning, dramatic smoke and steam rising, orange ember glow beneath grill bars, ASMR sound design, warm tungsten restaurant lighting, food commercial cinematography, 120fps ultra slow motion, Runway Gen-3 quality',
    description: '인스타그램·유튜브 광고에 바로 쓸 수 있는 고기 굽는 시즐 영상',
    tools: ['runway', 'kling'],
    tags: ['시즐영상', '슬로모션', 'ASMR', '광고'],
    tip: 'Kling AI는 한국어 입력도 지원해서 "삼겹살 굽는 슬로모션"으로도 시도해 보세요',
  },
  {
    id: 'res-vid-2',
    industryId: 'restaurant',
    category: 'video',
    title: '주방 비하인드 영상',
    prompt: 'Behind-the-scenes restaurant kitchen documentary video, multiple Korean chefs coordinating during dinner rush service, steam rising from multiple stainless pots, wok fire flaring dramatically, smooth tracking camera movement through busy kitchen, warm tungsten overhead lighting, cinema verité style, Arri Alexa color science, 24fps',
    description: '신뢰감을 주는 주방 운영 영상, 홈페이지 "소개" 섹션에 활용',
    tools: ['sora', 'runway'],
    tags: ['주방영상', '비하인드', '다큐', '신뢰'],
  },
  {
    id: 'res-vid-3',
    industryId: 'restaurant',
    category: 'video',
    title: '매장 소개 투어 영상',
    prompt: 'Smooth cinematic dolly camera glide through modern Korean restaurant, moving from entrance through dining area to private room, warm ambient lighting, elegant table settings, soft focus depth of field, real estate tour video style, natural morning light through windows, 4K, gentle orchestral background music implied, 30 second short film',
    description: '홈페이지 메인 배너나 네이버 플레이스 소개에 적합한 매장 투어',
    tools: ['runway', 'kling', 'sora'],
    tags: ['매장투어', '공간영상', '인테리어', '소개'],
  },
  {
    id: 'res-sns-1',
    industryId: 'restaurant',
    category: 'sns',
    title: '음식 릴스 콘셉트',
    prompt: '9:16 vertical Instagram Reels concept: extreme close-up of chopsticks lifting glistening Korean japchae noodles with sauce dripping in slow motion, smooth zoom out reveals full plating on wooden board, final frame shows restaurant name text overlay at bottom, 15 second video, ASMR sound design, trending food reel format, warm natural light',
    description: '알고리즘 반응이 좋은 음식 릴스 영상 기획안',
    tools: ['runway', 'kling'],
    tags: ['릴스', '인스타그램', '9:16', '바이럴'],
    tip: '영상 초반 3초에 강렬한 클로즈업을 넣어야 스킵을 방지할 수 있어요',
  },
  {
    id: 'res-sns-2',
    industryId: 'restaurant',
    category: 'sns',
    title: '메뉴 소개 카드뉴스',
    prompt: 'Series of 3 square 1:1 social media cards for Korean restaurant menu, Card 1: hero food photo with bold Korean title text overlay, Card 2: ingredient close-up details grid, Card 3: price and order CTA in warm amber brand color, consistent visual identity, clean minimal design, Instagram carousel format',
    description: '인스타그램 피드 카드뉴스 3장 세트 기획',
    tools: ['dall-e', 'midjourney'],
    tags: ['카드뉴스', '인스타그램', '피드', '메뉴소개'],
  },
  {
    id: 'res-sns-3',
    industryId: 'restaurant',
    category: 'sns',
    title: '틱톡 바이럴 포맷',
    prompt: 'TikTok-style satisfying food assembly video concept: individual Korean BBQ components (lettuce, garlic, kimchi, grilled meat) arranged one-by-one in satisfying time-lapse build-up, top-down angle, bright even studio lighting, symmetrical composition, ending with completed ssam wrap, no music needed, natural sound design, 15-30 seconds',
    description: '틱톡·쇼츠 바이럴에 최적화된 음식 조립 영상 포맷',
    tools: ['kling', 'runway'],
    tags: ['틱톡', '쇼츠', '바이럴', 'ASMR'],
  },

  /* ─────────────────── 카페 ─────────────────── */
  {
    id: 'cafe-img-1',
    industryId: 'cafe',
    category: 'image',
    title: '라떼아트 클로즈업',
    prompt: 'Overhead close-up photograph of perfect rosetta latte art in white ceramic cup, dark espresso ring with silky microfoam milk tulip design, natural morning window light from left, fresh roasted coffee beans scattered on wooden table beside cup, steam gently rising, Nikon Z7 90mm tilt-shift, ultra sharp, warm golden tones --ar 4:5 --v 6.1 --style raw',
    description: '카페 SNS 대표 이미지 및 메뉴판 음료 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['라떼아트', '음료사진', '카페', '클로즈업'],
    tip: '실제 촬영은 창가 자리에서 자연광을 이용하면 스튜디오 없이도 좋은 결과가 나와요',
  },
  {
    id: 'cafe-img-2',
    industryId: 'cafe',
    category: 'image',
    title: '디저트 플랫레이',
    prompt: 'Overhead flat lay of artisan Korean bakery pastries, butter croissants, fresh fruit tart, matcha roll cake, arranged on white marble with scattered powdered sugar, soft diffused window light, food styling, minimal Scandinavian aesthetic, warm film tones, 8K commercial bakery photography --ar 1:1 --v 6.1',
    description: '베이커리 메뉴 소개 및 SNS 업로드용 디저트 플랫레이',
    tools: ['midjourney', 'dall-e'],
    tags: ['디저트', '베이커리', '플랫레이', '화이트'],
  },
  {
    id: 'cafe-img-3',
    industryId: 'cafe',
    category: 'image',
    title: '감성 카페 인테리어',
    prompt: 'Cozy independent cafe interior, warm exposed brick wall, hanging Edison bulb lights, leather armchairs, wooden bookshelves, steam rising from ceramic mug on small table, rain visible through large window, moody atmospheric lighting, lifestyle photography, medium format film grain, golden hour bokeh --ar 16:9 --v 6.1',
    description: 'Google 플레이스·카카오맵 대표 인테리어 사진',
    tools: ['midjourney'],
    tags: ['카페인테리어', '감성', '분위기', '빈티지'],
  },
  {
    id: 'cafe-vid-1',
    industryId: 'cafe',
    category: 'video',
    title: '라떼아트 제작 영상',
    prompt: 'Slow motion close-up video of barista hand pouring steamed milk to create latte art in white cup, espresso swirling, silky microfoam forming rosetta pattern, soft focus, warm cafe ambient light, 4K 120fps, ASMR milk pouring sound, cinematic depth of field, 8 second loop, Runway Gen-3',
    description: '카페 SNS 콘텐츠 중 가장 반응이 좋은 라떼아트 제작 과정',
    tools: ['runway', 'kling'],
    tags: ['라떼아트', '슬로모션', 'ASMR', '바리스타'],
    tip: 'Kling AI로 "바리스타 라떼아트 붓기 슬로모션"을 한국어로 입력해도 잘 나와요',
  },
  {
    id: 'cafe-vid-2',
    industryId: 'cafe',
    category: 'video',
    title: '카페 분위기 영상',
    prompt: 'Cinematic ambiance video of cozy cafe on rainy day, window showing street rain, warm light inside, gentle steam from coffee, customers reading blurred in background, smooth slow pan camera movement, 24fps film look, soft piano music implied, 20 second atmosphere reel',
    description: '카페 홈페이지 메인 배너용 감성 분위기 영상',
    tools: ['sora', 'runway'],
    tags: ['분위기영상', '감성', '비오는날', '홍보'],
  },
  {
    id: 'cafe-sns-1',
    industryId: 'cafe',
    category: 'sns',
    title: '신메뉴 공개 릴스',
    prompt: '9:16 vertical Reels concept: product reveal of new seasonal drink, start with blurred mystery shot, focus pull reveals colorful Korean fruit ade in tall glass, condensation on glass, garnish being placed in slow motion, brand logo text fade in at end, 10 second video, bright natural light, Gen Z aesthetic',
    description: '신메뉴 출시 때 올리는 제품 공개 릴스 기획',
    tools: ['runway', 'kling'],
    tags: ['신메뉴', '공개', '릴스', '계절메뉴'],
  },
  {
    id: 'cafe-sns-2',
    industryId: 'cafe',
    category: 'sns',
    title: '카페 일상 스토리',
    prompt: 'Instagram Story series concept: 1) Morning sun through cafe windows 2) Barista preparing espresso close-up 3) Croissant freshly from oven 4) Today\'s special written on chalkboard 5) Cafe open sign with warm light, each frame 3 seconds, vertical 9:16, consistent warm filter, minimal text overlay',
    description: '매일 업로드하기 좋은 카페 일상 스토리 시리즈',
    tools: ['dall-e', 'midjourney'],
    tags: ['스토리', '일상', '매일콘텐츠', '시리즈'],
  },

  /* ─────────────────── 미용실 ─────────────────── */
  {
    id: 'beauty-img-1',
    industryId: 'beauty',
    category: 'image',
    title: '헤어 포트폴리오 샷',
    prompt: 'Professional beauty editorial portrait of Korean woman with perfect Korean perm hairstyle, soft studio lighting with diffused key light, pure white background, hair movement captured mid-flip, high fashion magazine quality, retouched skin, hair texture ultra detailed, Sony A9 85mm portrait lens --ar 3:4 --v 6.1 --style raw',
    description: '헤어샵 인스타그램 포트폴리오 및 서비스 소개 이미지',
    tools: ['midjourney', 'dall-e'],
    tags: ['헤어포트폴리오', '뷰티', '포트레이트', '에디토리얼'],
    tip: '실제 시술 후 촬영 시 창가에서 자연광 + 흰 배경천만으로도 전문 사진 효과를 낼 수 있어요',
  },
  {
    id: 'beauty-img-2',
    industryId: 'beauty',
    category: 'image',
    title: '살롱 인테리어',
    prompt: 'Modern luxury hair salon interior, white and gold minimalist decor, Hollywood vanity mirrors with warm bulb lighting rings, fresh flowers on stations, marble floors, natural light streaming through sheer curtains, architectural interior photography, real estate quality, wide angle 24mm --ar 16:9 --v 6.1',
    description: '네이버 블로그·예약 플랫폼 대표 매장 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['살롱인테리어', '화이트', '럭셔리', '공간사진'],
  },
  {
    id: 'beauty-img-3',
    industryId: 'beauty',
    category: 'image',
    title: '컬러 시술 디테일',
    prompt: 'Close-up detail shot of Korean balayage hair coloring process, colorist brush applying bleach on highlighted sections, foils being placed, rich chestnut to blonde gradient, soft salon lighting, professional beauty editorial style, selective focus, warm tones --ar 1:1 --v 6.1',
    description: '컬러·염색 서비스 소개를 위한 시술 과정 클로즈업',
    tools: ['midjourney'],
    tags: ['발레아쥬', '컬러', '시술과정', '클로즈업'],
  },
  {
    id: 'beauty-vid-1',
    industryId: 'beauty',
    category: 'video',
    title: '변신 비포&애프터',
    prompt: 'Split-screen or transition video concept: left side shows model with flat lifeless hair, smooth wipe transition to right side showing same model with voluminous Korean perm waves, beautiful salon lighting, 4K quality, satisfying reveal format, text overlay "Before → After", 10 second viral transformation format',
    description: '가장 강력한 미용실 SNS 콘텐츠, 비포애프터 변신 영상',
    tools: ['runway', 'kling'],
    tags: ['비포애프터', '변신', '퍼머넌트', '릴스'],
    tip: '실제 고객 동의를 받고 촬영한 비포애프터가 가장 신뢰도가 높아요',
  },
  {
    id: 'beauty-vid-2',
    industryId: 'beauty',
    category: 'video',
    title: '시술 과정 타임랩스',
    prompt: 'Time-lapse video of complete Korean hair coloring process, from application of foils to final reveal, stylists hands moving swiftly, warm salon lighting, overhead or 45-degree angle, satisfying color transformation visible through transparent foils, 30 second condensed version of 2-hour process, aesthetic GRWM format',
    description: '고객 불안감을 해소하는 시술 과정 공개 영상',
    tools: ['kling', 'runway'],
    tags: ['타임랩스', '시술과정', '컬러링', 'GRWM'],
  },
  {
    id: 'beauty-sns-1',
    industryId: 'beauty',
    category: 'sns',
    title: '헤어 스타일링 팁 릴스',
    prompt: '9:16 vertical tutorial Reels: Korean hair stylist demonstrating 3-step home styling hack for wavy hair, close-up hand movements with tools, Korean text callout overlays, satisfying before/after within same video, 30 seconds, bright even studio lighting, trending beauty tutorial format with fast cuts',
    description: '팔로워 유입에 효과적인 헤어 팁 교육 콘텐츠',
    tools: ['runway', 'kling'],
    tags: ['헤어팁', '튜토리얼', '릴스', '교육콘텐츠'],
  },
  {
    id: 'beauty-sns-2',
    industryId: 'beauty',
    category: 'sns',
    title: '이달의 트렌드 카드',
    prompt: 'Instagram carousel card series: 5 cards showing this month\'s trending Korean hair colors, Card 1: cover with bold Korean trend title, Cards 2-5: each featuring one color with model photo, color name, and price range, consistent grid layout, black and gold color scheme, fashion editorial aesthetic',
    description: '매월 업로드하기 좋은 트렌드 헤어 카드뉴스 시리즈',
    tools: ['midjourney', 'dall-e'],
    tags: ['트렌드', '카드뉴스', '월별콘텐츠', '인스타그램'],
  },

  /* ─────────────────── 병원 ─────────────────── */
  {
    id: 'clinic-img-1',
    industryId: 'clinic',
    category: 'image',
    title: '의료진 신뢰 사진',
    prompt: 'Professional medical portrait of Korean doctor in white lab coat, warm friendly smile, stethoscope around neck, clean modern hospital corridor background blurred, soft studio portrait lighting, trust-building professional healthcare photography, Sony A9 85mm, warm neutral color grade --ar 3:4 --v 6.1',
    description: '의원·병원 홈페이지 의료진 소개 섹션 전문 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['의료진', '포트레이트', '신뢰', '전문성'],
    tip: '흰 가운 위에 청진기 착용, 미소 표정이 환자 신뢰도를 가장 높여요',
  },
  {
    id: 'clinic-img-2',
    industryId: 'clinic',
    category: 'image',
    title: '진료실 인테리어',
    prompt: 'Clean modern Korean clinic interior, white and light blue color palette, natural wood accents, reception desk with soft ambient lighting, healthy plants, architectural photography, bright airy atmosphere, reassuring and calm aesthetic, wide angle 24mm, no people --ar 16:9 --v 6.1',
    description: '환자 불안감을 낮추는 밝고 깔끔한 의원 인테리어 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['의원인테리어', '청결', '신뢰', '공간사진'],
  },
  {
    id: 'clinic-vid-1',
    industryId: 'clinic',
    category: 'video',
    title: '병원 소개 영상',
    prompt: 'Cinematic hospital introduction video, smooth camera movements through bright modern Korean clinic, reception area to consultation rooms, warm reassuring lighting, friendly staff visible in background, documentary style, 30-45 second brand film, soft background music implied, 4K quality, trust-building healthcare brand aesthetic',
    description: '홈페이지 메인 및 유튜브 채널 개설용 병원 브랜드 영상',
    tools: ['runway', 'sora'],
    tags: ['병원소개', '브랜드필름', '신뢰', '전문성'],
  },
  {
    id: 'clinic-sns-1',
    industryId: 'clinic',
    category: 'sns',
    title: '건강 정보 카드뉴스',
    prompt: 'Instagram carousel medical information cards, 6 slides: Cover with bold health tip title, slides 2-5 with each tip as large icon + short Korean explanation, final slide with clinic contact CTA, clean white background, blue and green medical color palette, minimal professional infographic style, trustworthy healthcare brand',
    description: '팔로워 확보에 효과적인 건강 정보 교육 카드뉴스',
    tools: ['dall-e'],
    tags: ['건강정보', '카드뉴스', '교육', 'SNS마케팅'],
    tip: '의학적 정보는 반드시 의료진이 검수한 내용만 게시해야 해요',
  },
  {
    id: 'clinic-sns-2',
    industryId: 'clinic',
    category: 'sns',
    title: 'FAQ 릴스 시리즈',
    prompt: '9:16 vertical medical FAQ Reels: doctor on-camera answering common patient question in 30 seconds, text question overlay at start, clear verbal answer, friendly approachable tone, clean consultation room background, captions/subtitles shown, end card with booking CTA, educational healthcare content series',
    description: '신규 환자 유입에 효과적인 의사 직접 출연 FAQ 영상',
    tools: ['kling', 'runway'],
    tags: ['FAQ', '의사출연', '릴스', '교육'],
  },

  /* ─────────────────── 헬스·피트니스 ─────────────────── */
  {
    id: 'fitness-img-1',
    industryId: 'fitness',
    category: 'image',
    title: '퍼스널트레이닝 액션샷',
    prompt: 'Dynamic action shot of personal trainer working with client at modern Korean gym, dramatic backlit gym equipment, motion blur on weights, sweat drops visible, intense determined expressions, low angle heroic perspective, sports photography style, Sony A1 70-200mm, desaturated moody gym tones --ar 3:4 --v 6.1',
    description: 'PT 서비스 소개 및 회원 모집 광고 이미지',
    tools: ['midjourney', 'dall-e'],
    tags: ['퍼스널트레이닝', '액션샷', '헬스장', '동기부여'],
  },
  {
    id: 'fitness-img-2',
    industryId: 'fitness',
    category: 'image',
    title: '헬스장 시설 사진',
    prompt: 'Modern luxury gym interior, rows of premium cardio equipment, mirrored walls, perfect symmetrical composition, dramatic uplighting on equipment, no people, architectural photography, wide angle, dark slate floors, industrial aesthetic with warm accents, real estate quality 4K --ar 16:9 --v 6.1',
    description: '네이버 플레이스·홈페이지 시설 소개 사진',
    tools: ['midjourney'],
    tags: ['헬스장인테리어', '시설', '공간사진', '럭셔리'],
  },
  {
    id: 'fitness-vid-1',
    industryId: 'fitness',
    category: 'video',
    title: '운동 변신 스토리',
    prompt: 'Split-screen transformation story video: before/after of gym member physique change over 3 months, matching pose and lighting, motivational text overlay timeline, emotional music implied, 30-45 second short film format, 4K, desaturated cool grade with gold accent, inspiring sports brand aesthetic',
    description: '회원 등록 유도에 가장 강력한 실제 변신 스토리 영상',
    tools: ['runway', 'kling'],
    tags: ['변신스토리', '비포애프터', '모티베이션', '광고'],
    tip: '실제 회원 동의를 받은 변신 사례가 신규 등록에 가장 효과적이에요',
  },
  {
    id: 'fitness-vid-2',
    industryId: 'fitness',
    category: 'video',
    title: '운동 루틴 튜토리얼',
    prompt: '9:16 vertical workout tutorial Reels: trainer demonstrating 3-exercise home workout circuit, each exercise shown with counter overlay, correct form callout text, energetic editing with fast cuts between sets, gym or home background, upbeat implied music, 45-60 seconds, Korean text tips for each movement',
    description: '조회수·팔로워 성장에 효과적인 운동 튜토리얼 시리즈',
    tools: ['runway'],
    tags: ['운동튜토리얼', '릴스', '교육', '피트니스팁'],
  },
  {
    id: 'fitness-sns-1',
    industryId: 'fitness',
    category: 'sns',
    title: '동기부여 명언 카드',
    prompt: 'Motivational fitness quote card series for Instagram, bold Korean typography on dark gym aesthetic background with subtle barbell or dumbbell silhouettes, clean modern design, each card different composition but consistent brand color (dark gray + electric blue accent), 1:1 square format, 6 card set',
    description: '저장율 높은 동기부여 카드뉴스 - 꾸준한 팔로워 유지에 효과적',
    tools: ['dall-e'],
    tags: ['명언', '카드뉴스', '동기부여', '피트니스'],
  },
  {
    id: 'fitness-sns-2',
    industryId: 'fitness',
    category: 'sns',
    title: '회원 챌린지 릴스',
    prompt: '30-day fitness challenge social media campaign concept: 9:16 launch video showing diverse gym members doing same movement, fast-paced montage, challenge hashtag overlay, countdown timer graphic, call-to-action to join, Korean text, 15 second hype video format, energetic, community-building aesthetic',
    description: '커뮤니티 참여와 바이럴을 이끄는 챌린지 캠페인 기획',
    tools: ['runway', 'kling'],
    tags: ['챌린지', '커뮤니티', '캠페인', '바이럴'],
  },

  /* ─────────────────── 숙박·펜션 ─────────────────── */
  {
    id: 'accom-img-1',
    industryId: 'accommodation',
    category: 'image',
    title: '객실 인테리어',
    prompt: 'Interior of a luxury Korean pension guestroom, natural wood beams, floor-to-ceiling windows with mountain forest view, king bed with white linen, warm pendant lights, reading nook corner, golden hour sunlight, architectural hospitality photography, medium format quality, ultra detail, Airbnb-style hero shot --ar 16:9 --v 6.1',
    description: '예약 플랫폼·홈페이지 메인 객실 소개 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['객실인테리어', '펜션', '감성숙소', '자연'],
    tip: '예약 플랫폼 대표 사진은 16:9 비율의 자연광 객실 사진이 예약률을 높여요',
  },
  {
    id: 'accom-img-2',
    industryId: 'accommodation',
    category: 'image',
    title: '전경·부대시설',
    prompt: 'Aerial drone view of Korean mountain pension complex, wooden buildings surrounded by autumn foliage, morning mist in valleys, winding forest path, outdoor deck with chairs, resort-style architecture harmonizing with nature, golden sunrise light, landscape photography, DJI Air 3 quality --ar 16:9 --v 6.1',
    description: '숙소 위치·분위기 전달에 효과적인 외관·전경 사진',
    tools: ['midjourney'],
    tags: ['드론샷', '전경', '가을', '자연숙소'],
  },
  {
    id: 'accom-img-3',
    industryId: 'accommodation',
    category: 'image',
    title: '조식 테이블 세팅',
    prompt: 'Korean pension breakfast table setting, natural wooden table, traditional white ceramic dishes, fresh seasonal side dishes, warm morning light through window, green valley view in background, lifestyle hospitality photography, warm film tones, overhead slight angle, editorial hotel quality --ar 3:2 --v 6.1',
    description: '조식 서비스 홍보 및 예약률 향상을 위한 식사 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['조식', '테이블세팅', '한식', '숙소'],
  },
  {
    id: 'accom-vid-1',
    industryId: 'accommodation',
    category: 'video',
    title: '숙소 투어 영상',
    prompt: 'Cinematic walkthrough tour of Korean mountain pension, smooth gimbal camera movement through entrance to room to outdoor deck with valley view, warm evening golden hour lighting, peaceful ambient sound design, 60-90 second virtual tour format, 4K, lifestyle hospitality cinematography, luxury travel video aesthetic',
    description: '예약 전환율을 높이는 숙소 전체 투어 영상',
    tools: ['runway', 'sora'],
    tags: ['숙소투어', '가상투어', '예약', '홍보'],
  },
  {
    id: 'accom-vid-2',
    industryId: 'accommodation',
    category: 'video',
    title: '계절 감성 영상',
    prompt: 'Seasonal atmosphere short film for Korean pension: spring cherry blossoms falling on wooden deck, summer fireflies at night, autumn maple leaves falling, winter snow on roof, each 5-second sequence, smooth transitions, ambient nature sounds, 25 second loop, cinematic lens flares, travel lifestyle aesthetic',
    description: '사계절 내내 활용 가능한 감성 숙소 브랜드 영상',
    tools: ['sora', 'runway'],
    tags: ['계절영상', '감성', '자연', '브랜딩'],
  },
  {
    id: 'accom-sns-1',
    industryId: 'accommodation',
    category: 'sns',
    title: '감성 숙소 릴스',
    prompt: '9:16 vertical lifestyle Reels for Korean pension: morning sequence - sunrise through curtains, coffee on outdoor deck, misty mountain view, breakfast preparation, final outdoor shot with couple, smooth slow transitions, ambient morning sound, 30 seconds, Pinterest aesthetic travel vlog format, warm vintage filter',
    description: '저장·공유율 높은 감성 숙소 체험 릴스 기획',
    tools: ['runway', 'kling'],
    tags: ['감성릴스', '숙소체험', '여행', '모닝루틴'],
  },
  {
    id: 'accom-sns-2',
    industryId: 'accommodation',
    category: 'sns',
    title: '특가 프로모션 카드',
    prompt: 'Instagram promotion card for pension seasonal deal, bold Korean price announcement, before/after strikethrough pricing, limited time urgency badge, beautiful room photo as background with dark overlay, clean sans-serif typography, warm amber CTA button color, 1:1 square format, trust badges at bottom',
    description: '비수기 예약 유도를 위한 특가 프로모션 홍보 카드',
    tools: ['dall-e'],
    tags: ['프로모션', '특가', '광고', '카드뉴스'],
  },

  /* ─────────────────── 쇼핑·의류 ─────────────────── */
  {
    id: 'shop-img-1',
    industryId: 'shopping',
    category: 'image',
    title: '의류 룩북 사진',
    prompt: 'Korean fashion lookbook photography, model wearing minimalist monochrome Korean street style outfit, shot on clean white paper background with subtle drop shadow, full body and detail shots, soft studio lighting, editorial fashion quality, film grain, neutral natural tones, Celine/Acne Studios aesthetic --ar 3:4 --v 6.1 --style raw',
    description: '온라인 쇼핑몰·인스타그램 쇼핑 태그용 의류 상품 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['룩북', '패션사진', '상품사진', '에디토리얼'],
    tip: '배경은 흰 벽 + 흰 바닥 조합이 어떤 스타일에도 잘 어울려요',
  },
  {
    id: 'shop-img-2',
    industryId: 'shopping',
    category: 'image',
    title: '상품 디테일 클로즈업',
    prompt: 'Close-up product photography of Korean fashion accessory details, fabric texture macro shot, stitching quality visible, zipper pull close-up, label tag, professional product photography lighting, white seamless background, 8K ultra detail, Amazon/Coupang quality listing images --ar 1:1 --v 6.1 --style raw',
    description: '상품 품질 신뢰도를 높이는 디테일 클로즈업 이미지',
    tools: ['midjourney', 'dall-e'],
    tags: ['상품사진', '디테일', '클로즈업', '온라인쇼핑몰'],
  },
  {
    id: 'shop-vid-1',
    industryId: 'shopping',
    category: 'video',
    title: '신상품 언박싱 릴스',
    prompt: '9:16 product unboxing Reels for Korean fashion brand, clean white table setup, hands opening minimalist branded packaging, tissue paper reveal, product lay flat reveal, satisfying sound design, 15 second format, bright studio lighting, fast cuts between angles, trending unboxing format with Korean text overlay',
    description: '신제품 출시 때 필수인 언박싱 콘텐츠 기획',
    tools: ['runway', 'kling'],
    tags: ['언박싱', '신상', '릴스', '제품공개'],
  },
  {
    id: 'shop-sns-1',
    industryId: 'shopping',
    category: 'sns',
    title: '코디 스타일링 릴스',
    prompt: '9:16 styling Reels: Get Ready With Me format, outfit transition reveals for same item styled 3 different ways, quick cuts, trending transition effects, Korean text "이렇게도 입어요" overlay, 30 seconds, bright consistent lighting, Pinterest fashion aesthetic, body positive diverse styling',
    description: '상품 활용도를 보여주는 코디 제안 릴스 - 구매 전환율 향상',
    tools: ['runway', 'kling'],
    tags: ['코디릴스', 'GRWM', '스타일링', '구매전환'],
  },
  {
    id: 'shop-sns-2',
    industryId: 'shopping',
    category: 'sns',
    title: '세일 프로모션 카드',
    prompt: 'Korean fashion sale promotion Instagram post, bold typography "최대 70% 세일", product collage grid in background, urgency countdown element, clean white space, brand signature color accent, 1:1 and 9:16 versions, high-impact commercial design, matching story and feed format pair',
    description: '시즌 세일·이벤트 홍보를 위한 임팩트 있는 프로모션 포스터',
    tools: ['dall-e'],
    tags: ['세일', '프로모션', '광고포스터', '이벤트'],
  },

  /* ─────────────────── 학원·교육 ─────────────────── */
  {
    id: 'edu-img-1',
    industryId: 'education',
    category: 'image',
    title: '수업 현장 사진',
    prompt: 'Korean tutoring academy classroom scene, engaged students and friendly teacher at whiteboard, modern bright classroom interior, natural light, candid lifestyle photography, warm encouraging atmosphere, editorial education brand photography, diversity represented --ar 16:9 --v 6.1',
    description: '학원 신뢰도와 분위기를 전달하는 수업 현장 사진',
    tools: ['midjourney', 'dall-e'],
    tags: ['수업현장', '학원', '교육', '라이프스타일'],
    tip: '실제 학생·강사 사진은 반드시 동의서를 받고 활용해야 해요',
  },
  {
    id: 'edu-vid-1',
    industryId: 'education',
    category: 'video',
    title: '합격 스토리 영상',
    prompt: 'Emotional success story short film: Korean student opening acceptance letter, family celebration scene, student testimonial to camera, study montage flashback, inspiring music implied, 45-60 seconds, warm cinematic grade, documentary storytelling style, trust-building brand content',
    description: '신규 수강생 등록 유도에 강력한 합격·성과 스토리 영상',
    tools: ['runway', 'sora'],
    tags: ['합격스토리', '성과', '광고', '신뢰'],
  },
  {
    id: 'edu-sns-1',
    industryId: 'education',
    category: 'sns',
    title: '학습 팁 카드뉴스',
    prompt: 'Study tips Instagram carousel, 6 cards: Cover card with bold "수능 D-100 학습법" title, each subsequent card with one actionable study hack, clean icon + short Korean text layout, blue and white academic color scheme, consistent typography, encouraging tone, final CTA card with academy contact',
    description: '팔로워 증가와 신뢰도 구축에 효과적인 학습 팁 카드뉴스',
    tools: ['dall-e'],
    tags: ['학습팁', '카드뉴스', '교육콘텐츠', '수능'],
  },
];

export function getPromptsByIndustry(industryId: string): PromptItem[] {
  return ALL_PROMPTS.filter((p) => p.industryId === industryId);
}

export function getPromptsByCategory(industryId: string, category: PromptCategory): PromptItem[] {
  return ALL_PROMPTS.filter((p) => p.industryId === industryId && p.category === category);
}
