import { MenuItem } from '@/types/menu';

export const MENU_ITEMS: MenuItem[] = [
  // ── 면류 ──────────────────────────────────────────────
  {
    id: 'menu-101',
    name: 'Jajangmyeon',
    nameKo: '짜장면',
    description: '춘장 볶음 소스에 돼지고기, 양파, 감자를 넣은 국민 중식',
    price: 8000,
    category: 'noodle',
    tags: ['popular'],
    allergens: ['gluten', 'soy'],
    available: true,
    imageUrl: '/demo/menu/menu-jjajangmyeon.jpg',
  },
  {
    id: 'menu-102',
    name: 'Jjamppong',
    nameKo: '짬뽕',
    description: '해물과 채소를 넣은 얼큰한 빨간 국물 면',
    price: 10000,
    category: 'noodle',
    tags: ['popular', 'spicy'],
    allergens: ['gluten', 'shellfish'],
    available: true,
    imageUrl: '/demo/menu/menu-jjamppong.jpg',
  },
  {
    id: 'menu-103',
    name: 'Jaengban Jajang',
    nameKo: '쟁반짜장',
    description: '넓은 쟁반에 담아 함께 비벼 먹는 짜장, 2~3인분',
    price: 25000,
    category: 'noodle',
    tags: ['popular', 'sharing'],
    allergens: ['gluten', 'soy'],
    available: true,
    imageUrl: '/demo/menu/menu-jaengban-jjajang.jpg',
  },
  {
    id: 'menu-104',
    name: 'Baek Jjamppong',
    nameKo: '백짬뽕',
    description: '해물 육수로 끓인 하얗고 진한 국물의 짬뽕',
    price: 13000,
    category: 'noodle',
    tags: [],
    allergens: ['gluten', 'shellfish'],
    available: true,
    imageUrl: '/demo/menu/menu-baek-jjamppong.jpg',
  },

  // ── 밥류 ──────────────────────────────────────────────
  {
    id: 'menu-201',
    name: 'Jjamppong Bap',
    nameKo: '짬뽕밥',
    description: '짬뽕 국물에 밥을 말아 먹는 얼큰한 한 그릇',
    price: 11000,
    category: 'rice',
    tags: ['spicy'],
    allergens: ['shellfish'],
    available: true,
  },
  {
    id: 'menu-202',
    name: 'Shrimp Fried Rice',
    nameKo: '새우볶음밥',
    description: '탱글한 새우와 채소를 넣어 고온에 볶은 황금 볶음밥',
    price: 12000,
    category: 'rice',
    tags: ['popular'],
    allergens: ['shellfish', 'egg'],
    available: true,
    imageUrl: '/demo/menu/menu-shrimp-friedrice.jpg',
  },
  {
    id: 'menu-203',
    name: 'Haemul Japchae Bap',
    nameKo: '해물잡탕밥',
    description: '각종 해물과 채소를 진한 소스로 볶아 밥 위에 올린 요리',
    price: 18000,
    category: 'rice',
    tags: [],
    allergens: ['shellfish', 'egg'],
    available: true,
  },
  {
    id: 'menu-204',
    name: 'Japchae Bap',
    nameKo: '잡채밥',
    description: '당면과 각종 채소 잡채를 밥 위에 올린 중식풍 잡채밥',
    price: 13000,
    category: 'rice',
    tags: [],
    allergens: ['gluten', 'soy'],
    available: true,
  },

  // ── 요리 ──────────────────────────────────────────────
  {
    id: 'menu-301',
    name: 'Tangsuyuk (S)',
    nameKo: '탕수육(소)',
    description: '바삭한 튀김옷에 새콤달콤 소스, 소(2~3인)',
    price: 25000,
    category: 'dish',
    tags: ['popular', 'sharing'],
    allergens: ['gluten', 'egg'],
    available: true,
  },
  {
    id: 'menu-302',
    name: 'Tangsuyuk (L)',
    nameKo: '탕수육(대)',
    description: '바삭한 튀김옷에 새콤달콤 소스, 대(4~5인)',
    price: 38000,
    category: 'dish',
    tags: ['sharing'],
    allergens: ['gluten', 'egg'],
    available: true,
  },
  {
    id: 'menu-303',
    name: 'Ganpunggi',
    nameKo: '깐풍기',
    description: '닭고기를 바삭하게 튀겨 매콤 달콤한 깐풍 소스로 버무린 요리',
    price: 28000,
    category: 'dish',
    tags: ['popular', 'spicy'],
    allergens: ['gluten', 'egg'],
    available: true,
  },
  {
    id: 'menu-304',
    name: 'Yuringi',
    nameKo: '유린기',
    description: '부드럽게 튀긴 닭고기에 향긋한 파 소스를 뿌린 요리',
    price: 26000,
    category: 'dish',
    tags: ['popular'],
    allergens: ['gluten', 'egg', 'soy'],
    available: true,
  },
  {
    id: 'menu-305',
    name: 'Guobaorou',
    nameKo: '꿔바로우',
    description: '얇게 썬 돼지고기를 바삭하게 튀겨 새콤달콤 소스로 마무리',
    price: 24000,
    category: 'dish',
    tags: [],
    allergens: ['gluten', 'egg'],
    available: true,
  },
  {
    id: 'menu-306',
    name: 'Menbosa',
    nameKo: '멘보샤',
    description: '식빵 사이에 새우 소를 넣고 황금빛으로 튀긴 중식 스타일 샌드위치',
    price: 22000,
    category: 'dish',
    tags: [],
    allergens: ['gluten', 'shellfish', 'egg'],
    available: true,
  },
  {
    id: 'menu-307',
    name: 'Gansho Saewoo',
    nameKo: '깐쇼새우',
    description: '왕새우를 바삭하게 튀겨 매콤 달콤한 깐쇼 소스에 볶은 요리',
    price: 32000,
    category: 'dish',
    tags: ['spicy'],
    allergens: ['gluten', 'shellfish', 'egg'],
    available: true,
  },
  {
    id: 'menu-308',
    name: 'Crab Egg Soup',
    nameKo: '게살계란탕',
    description: '게살과 부드러운 계란을 넣어 끓인 걸쭉하고 담백한 중식 탕',
    price: 16000,
    category: 'dish',
    tags: [],
    allergens: ['shellfish', 'egg'],
    available: true,
  },

  // ── 세트메뉴 ───────────────────────────────────────────
  {
    id: 'menu-401',
    name: 'Chinese Set',
    nameKo: '중화세트',
    description: '짜장면 + 깐풍기 + 크림새우 + 군만두 + 스푼밥',
    price: 16000,
    category: 'set',
    tags: ['popular', 'best-value'],
    allergens: ['gluten', 'shellfish', 'egg'],
    available: true,
  },
  {
    id: 'menu-402',
    name: 'Family Set',
    nameKo: '가정세트',
    description: '짬뽕 + 유린기 + 군만두 + 멘보샤 + 스푼밥',
    price: 16000,
    category: 'set',
    tags: ['best-value'],
    allergens: ['gluten', 'shellfish', 'egg'],
    available: true,
  },

  // ── 식사보조 ───────────────────────────────────────────
  {
    id: 'menu-501',
    name: 'Fried Dumplings',
    nameKo: '군만두',
    description: '고기와 채소 소를 넣어 바삭하게 구운 만두',
    price: 6000,
    category: 'side',
    tags: ['popular'],
    allergens: ['gluten', 'egg'],
    available: true,
  },
];

export function getMenuItems(): MenuItem[] {
  return MENU_ITEMS;
}

export function getMenuItemById(id: string): MenuItem | undefined {
  return MENU_ITEMS.find((item) => item.id === id);
}

export function getMenuByCategory(category: string): MenuItem[] {
  return MENU_ITEMS.filter((item) => item.category === category && item.available);
}
