// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/hancandy" | "/admin/korean" | "/admin/menu" | "/admin/menu-print" | "/admin/orders" | "/admin/payments" | "/admin/print" | "/admin/reservations" | "/admin/robots" | "/admin/settlement" | "/admin/tax" | "/chat" | "/demo" | "/hancandy" | "/hancandy/cart" | "/hancandy/chat" | "/hancandy/products" | "/hancandy/products/[id]" | "/korean" | "/korean/chat" | "/korean/dashboard" | "/korean/learn" | "/korean/test" | "/login" | "/menu" | "/myspace" | "/payment" | "/print" | "/print/chat" | "/print/files" | "/print/labels" | "/print/quote" | "/print/status" | "/print/upload" | "/products/sr05" | "/prompts" | "/reservation" | "/signup" | "/tax" | "/tax/calculator" | "/tax/calendar" | "/tax/chat" | "/tax/reservation" | "/tracking"
type AppRouteHandlerRoutes = "/api/chat" | "/api/hancandy/chat" | "/api/korean/chat" | "/api/korean/progress" | "/api/korean/students" | "/api/korean/test" | "/api/menu" | "/api/orders" | "/api/orders/[id]" | "/api/payments" | "/api/print/chat" | "/api/print/clients" | "/api/print/clients/[id]" | "/api/print/clients/[id]/files" | "/api/print/labels" | "/api/print/labels/[id]" | "/api/print/orders" | "/api/print/orders/[id]" | "/api/print/quote" | "/api/print/search" | "/api/recommend" | "/api/refunds" | "/api/reservations" | "/api/reservations/[id]" | "/api/reservations/predict-wait" | "/api/robots" | "/api/robots/[id]" | "/api/settlement" | "/api/stats" | "/api/tax/chat" | "/api/tax/reservations"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/admin/print" | "/hancandy" | "/korean" | "/print" | "/tax"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/hancandy": {}
  "/admin/korean": {}
  "/admin/menu": {}
  "/admin/menu-print": {}
  "/admin/orders": {}
  "/admin/payments": {}
  "/admin/print": {}
  "/admin/reservations": {}
  "/admin/robots": {}
  "/admin/settlement": {}
  "/admin/tax": {}
  "/api/chat": {}
  "/api/hancandy/chat": {}
  "/api/korean/chat": {}
  "/api/korean/progress": {}
  "/api/korean/students": {}
  "/api/korean/test": {}
  "/api/menu": {}
  "/api/orders": {}
  "/api/orders/[id]": { "id": string; }
  "/api/payments": {}
  "/api/print/chat": {}
  "/api/print/clients": {}
  "/api/print/clients/[id]": { "id": string; }
  "/api/print/clients/[id]/files": { "id": string; }
  "/api/print/labels": {}
  "/api/print/labels/[id]": { "id": string; }
  "/api/print/orders": {}
  "/api/print/orders/[id]": { "id": string; }
  "/api/print/quote": {}
  "/api/print/search": {}
  "/api/recommend": {}
  "/api/refunds": {}
  "/api/reservations": {}
  "/api/reservations/[id]": { "id": string; }
  "/api/reservations/predict-wait": {}
  "/api/robots": {}
  "/api/robots/[id]": { "id": string; }
  "/api/settlement": {}
  "/api/stats": {}
  "/api/tax/chat": {}
  "/api/tax/reservations": {}
  "/chat": {}
  "/demo": {}
  "/hancandy": {}
  "/hancandy/cart": {}
  "/hancandy/chat": {}
  "/hancandy/products": {}
  "/hancandy/products/[id]": { "id": string; }
  "/korean": {}
  "/korean/chat": {}
  "/korean/dashboard": {}
  "/korean/learn": {}
  "/korean/test": {}
  "/login": {}
  "/menu": {}
  "/myspace": {}
  "/payment": {}
  "/print": {}
  "/print/chat": {}
  "/print/files": {}
  "/print/labels": {}
  "/print/quote": {}
  "/print/status": {}
  "/print/upload": {}
  "/products/sr05": {}
  "/prompts": {}
  "/reservation": {}
  "/signup": {}
  "/tax": {}
  "/tax/calculator": {}
  "/tax/calendar": {}
  "/tax/chat": {}
  "/tax/reservation": {}
  "/tracking": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/admin/print": never
  "/hancandy": never
  "/korean": never
  "/print": never
  "/tax": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
