// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(customer)/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/(customer)/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(customer)/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/menu">> = Specific
  const handler = {} as typeof import("../../../src/app/(customer)/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(customer)/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment">> = Specific
  const handler = {} as typeof import("../../../src/app/(customer)/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(customer)/reservation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reservation">> = Specific
  const handler = {} as typeof import("../../../src/app/(customer)/reservation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(customer)/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tracking">> = Specific
  const handler = {} as typeof import("../../../src/app/(customer)/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/hancandy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hancandy">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/hancandy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/korean/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/korean">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/korean/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/menu-print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu-print">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/menu-print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/print">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reservations">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/robots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/robots">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/robots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settlement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settlement">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settlement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tax">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../../src/app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hancandy/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hancandy/cart">> = Specific
  const handler = {} as typeof import("../../../src/app/hancandy/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hancandy/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hancandy/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/hancandy/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hancandy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hancandy">> = Specific
  const handler = {} as typeof import("../../../src/app/hancandy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hancandy/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hancandy/products/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/hancandy/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hancandy/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hancandy/products">> = Specific
  const handler = {} as typeof import("../../../src/app/hancandy/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/korean/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/korean/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/korean/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/korean/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/korean/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/korean/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/korean/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/korean/learn">> = Specific
  const handler = {} as typeof import("../../../src/app/korean/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/korean/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/korean">> = Specific
  const handler = {} as typeof import("../../../src/app/korean/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/korean/test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/korean/test">> = Specific
  const handler = {} as typeof import("../../../src/app/korean/test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/myspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/myspace">> = Specific
  const handler = {} as typeof import("../../../src/app/myspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/print/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/print/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/print/files/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print/files">> = Specific
  const handler = {} as typeof import("../../../src/app/print/files/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/print/labels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print/labels">> = Specific
  const handler = {} as typeof import("../../../src/app/print/labels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print">> = Specific
  const handler = {} as typeof import("../../../src/app/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/print/quote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print/quote">> = Specific
  const handler = {} as typeof import("../../../src/app/print/quote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/print/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print/status">> = Specific
  const handler = {} as typeof import("../../../src/app/print/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/print/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/print/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/products/sr05/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/sr05">> = Specific
  const handler = {} as typeof import("../../../src/app/products/sr05/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prompts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prompts">> = Specific
  const handler = {} as typeof import("../../../src/app/prompts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tax/calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tax/calculator">> = Specific
  const handler = {} as typeof import("../../../src/app/tax/calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tax/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tax/calendar">> = Specific
  const handler = {} as typeof import("../../../src/app/tax/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tax/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tax/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/tax/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tax">> = Specific
  const handler = {} as typeof import("../../../src/app/tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tax/reservation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tax/reservation">> = Specific
  const handler = {} as typeof import("../../../src/app/tax/reservation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/hancandy/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hancandy/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/hancandy/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/korean/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/korean/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/korean/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/korean/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/korean/progress">> = Specific
  const handler = {} as typeof import("../../../src/app/api/korean/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/korean/students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/korean/students">> = Specific
  const handler = {} as typeof import("../../../src/app/api/korean/students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/korean/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/korean/test">> = Specific
  const handler = {} as typeof import("../../../src/app/api/korean/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/menu/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu">> = Specific
  const handler = {} as typeof import("../../../src/app/api/menu/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/print/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/print/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/print/clients/[id]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print/clients/[id]/files">> = Specific
  const handler = {} as typeof import("../../../src/app/api/print/clients/[id]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/print/clients/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print/clients/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/print/clients/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/print/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print/clients">> = Specific
  const handler = {} as typeof import("../../../src/app/api/print/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/print/labels/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print/labels/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/print/labels/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/print/labels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print/labels">> = Specific
  const handler = {} as typeof import("../../../src/app/api/print/labels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/print/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/print/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/print/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/print/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/print/quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print/quote">> = Specific
  const handler = {} as typeof import("../../../src/app/api/print/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/print/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/print/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/print/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/recommend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommend">> = Specific
  const handler = {} as typeof import("../../../src/app/api/recommend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/refunds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/refunds">> = Specific
  const handler = {} as typeof import("../../../src/app/api/refunds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reservations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reservations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reservations/predict-wait/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/predict-wait">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reservations/predict-wait/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/robots/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/robots/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/robots/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/robots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/robots">> = Specific
  const handler = {} as typeof import("../../../src/app/api/robots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/settlement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settlement">> = Specific
  const handler = {} as typeof import("../../../src/app/api/settlement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tax/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tax/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tax/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tax/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tax/reservations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tax/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(customer)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(customer)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/print/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/print">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/print/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hancandy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/hancandy">> = Specific
  const handler = {} as typeof import("../../../src/app/hancandy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/korean/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/korean">> = Specific
  const handler = {} as typeof import("../../../src/app/korean/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/print/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/print">> = Specific
  const handler = {} as typeof import("../../../src/app/print/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tax/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tax">> = Specific
  const handler = {} as typeof import("../../../src/app/tax/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
